name: rsync with SSH agent

on:
  push:
    branches: [ "persona/gaming" ]
  pull_request:
    branches: [ "persona/gaming" ]
  workflow_dispatch:

jobs:
  upload_files:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: mschmitt/rsync-with-ssh-agent@v2
        with:
          SSH_KEY: ${{ secrets.SSH_KEY3 }}
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE3 }}
          SSH_USER: ${{ secrets.SSH_USER3 }}
          SSH_HOST: ${{ secrets.SSH_HOST3 }}
          RSYNC_OPTIONS: '--exclude ".*" --recursive --delete --verbose'
