name: rsync with SSH agent

on:
  push:
    branches: [ "persona/professional" ]
  pull_request:
    branches: [ "persona/professional" ]
  workflow_dispatch:

jobs:
  upload_files:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: mschmitt/rsync-with-ssh-agent@v2
        with:
          SSH_KEY: ${{ secrets.SSH_KEY2 }}
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE2 }}
          SSH_USER: ${{ secrets.SSH_USER2 }}
          SSH_HOST: ${{ secrets.SSH_HOST2 }}
          RSYNC_OPTIONS: '--include=.htaccess --exclude ".*" --recursive --delete-excluded --verbose'
